### ISSUE TITLE
Request for upload speed info

### ISSUE THREAD

**Issue by kodxana** [spectre10/fs-cli#2]
Hi there! Is there a way to display speed of the transfering process instead of just showing total file size?

**Comment by spectre10** [comment]
Yes, it is the next planned feature. I will implement it in at max a week.

**Comment by spectre10** [comment]
Completed in  ([#1141112](https://github.com/spectre10/fileshare-cli/commit/1141112ccf3be5d99726412fe82c5d948dcf0001))
